[2024-01-26 15:38:24,174] 20 root - INFO - This is my 1st testing
[2024-01-26 15:38:24,633] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4000
 * Running on http://172.18.0.12:4000
[2024-01-26 15:38:24,634] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-01-26 15:38:34,841] 96 werkzeug - INFO - 172.18.0.2 - - [26/Jan/2024 15:38:34] "GET / HTTP/1.1" 200 -
[2024-01-26 15:38:34,919] 96 werkzeug - INFO - 172.18.0.2 - - [26/Jan/2024 15:38:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-01-26 15:38:46,990] 96 werkzeug - INFO - 172.18.0.2 - - [26/Jan/2024 15:38:46] "GET /predict HTTP/1.1" 200 -
[2024-01-26 15:38:55,315] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "/config/workspace/env/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/config/workspace/env/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/config/workspace/env/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/workspace/env/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 27, in predict_datapoint
    final_data = data.get_data_as_dataframe(data)
TypeError: get_data_as_dataframe() takes 1 positional argument but 2 were given
[2024-01-26 15:38:55,316] 96 werkzeug - INFO - 172.18.0.2 - - [26/Jan/2024 15:38:55] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
